apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user-manager-server.fullname" . }}
  labels:
    {{- include "user-manager-server.labels" . | nindent 4 }}
data:
  config.yaml: |
    httpPort: {{ .Values.httpPort }}
    grpcPort: {{ .Values.grpcPort }}
    internalGrpcPort: {{ .Values.internalGrpcPort }}
    defaultOrganization:
      title: {{ .Values.defaultOrganization.title }}
      userIds:
      {{- toYaml .Values.defaultOrganization.userIds | nindent 6 }}
      tenantId: {{ .Values.defaultOrganization.tenantId }}
    defaultProject:
      title: {{ .Values.defaultProject.title }}
      kubernetesNamespace: {{ .Values.defaultProject.kubernetesNamespace }}
      userIds:
      {{- toYaml .Values.defaultProject.userIds | nindent 6 }}
    database:
      host: {{ .Values.global.database.host }}
      port: {{ .Values.global.database.port }}
      database: {{ .Values.database.database }}
      username: {{ .Values.global.database.username }}
      passwordEnvName: DB_PASSWORD
    auth:
      enable: {{ .Values.global.auth.enable }}
      rbacInternalServerAddr: {{ .Values.global.auth.rbacInternalServerAddr }}
