apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "user-mananger-server.fullname" . }}-http
  labels:
    {{- include "user-mananger-server.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.global.ingress.ingressClassName }}
  rules:
  - http:
      paths:
      - path: /v1/users
        pathType: Prefix
        backend:
          service:
            name: {{ include "user-mananger-server.fullname" . }}-http
            port:
              number: {{ .Values.httpPort }}
