apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-manager-server.fullname" . }}-http
  labels:
    {{- include "user-manager-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "user-manager-server.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-manager-server.fullname" . }}-grpc
  labels:
    {{- include "user-manager-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: {{ .Values.grpcPort }}
    protocol: TCP
    targetPort: grpc
  selector:
    {{- include "user-manager-server.selectorLabels" . | nindent 4 }}


---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-manager-server.fullname" . }}-internal-grpc
  labels:
    {{- include "user-manager-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: {{ .Values.internalGrpcPort }}
    protocol: TCP
    targetPort: internal-grpc
  selector:
    {{- include "user-manager-server.selectorLabels" . | nindent 4 }}
