httpPort: 8080
grpcPort: 8081
internalGrpcPort: 8082

defaultOrganization:
  title: Default Organization
  userIds:
  - admin@example.com

defaultProject:
  title: Default Project
  kubernetesNamespace: default

debug:
  standalone: true
  sqlitePath: /tmp/user_manager.db
