httpPort: 8080
grpcPort: 8081
internalGrpcPort: 8082

defaultOrganization:
  name: Default Organization
  userIds:
  - admin@example.com

defaultProject:
  name: Default Project
  kubernetesNamespace: default
  userIds:
  - admin@example.com

debug:
  standalone: true
  sqlitePath: /tmp/user_manager.db
