global:
  database:
    host:
    port:
    username:

  databaseSecret:
    name:
    key:

  ingress:
    ingressClassName:
    annotations:
    tls:
      hosts:
      secretName:

  auth:
    enable:
    rbacInternalServerAddr:

httpPort: 8080
grpcPort: 8081
internalGrpcPort: 8082

database:
  database: user_manager

defaultOrganization:
  title: Default Organization
  userIds:
  - admin@example.com
  tenantId: default-tenant-id

defaultProject:
  title: Default Project
  kubernetesNamespace: default
  userIds:
  - admin@example.com

replicaCount: 1
image:
  repository: public.ecr.aws/v8n3t7y5/llm-operator/user-manager-server
  pullPolicy: IfNotPresent

version:
